### ISSUE TITLE
Change line 9 of README.MD

### ISSUE THREAD

**Issue by liu7d7** [ChiquitaV2/MineClient#1]
FROM "Download the lastest compiled version of MineClient for your Minecraft version [from the releases section](https://github.com/ChiquitaV2/MineClinent/releases)"

TO "Download the latest compiled version of MineClient for your Minecraft version [from the releases section](https://github.com/ChiquitaV2/MineClient/releases)"

**Comment by ChiquitaV2** [comment]
Wow I really did that also isn't it cool I can change that from my phone
